DROP TABLE IF EXISTS APPUSER;
DROP TABLE IF EXISTS APPUSERROLE;



CREATE TABLE IF NOT EXISTS APPUSER (
  ID             BIGSERIAL PRIMARY KEY,
  NAME           VARCHAR(25) NOT NULL,
  SURNAME        VARCHAR(25) NOT NULL,
  PASSWORD       VARCHAR(60) NOT NULL DEFAULT ('test'),
  EMAIL          TEXT        NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS APPUSERROLE(
ID BIGSERIAL PRIMARY KEY,
APPUSER_FK bigint REFERENCES APPUSER(ID),
ROLE VARCHAR(25) NOT NULL
);
INSERT INTO appuser (name, surname, email) VALUES
  ('zbyszko', 'zBogdanca', 'admin@gmail.com'),
  ('tadzio', 'spod sklepu', 'tadek@gmail.com');

INSERT INTO APPUSERROLE(APPUSER_FK, ROLE) VALUES
((SELECT ID FROM APPUSER WHERE EMAIL = 'admin@gmail.com'),'USER'),
((SELECT ID FROM APPUSER WHERE EMAIL = 'tadek@gmail.com'),'USER'),
((SELECT ID FROM APPUSER WHERE EMAIL = 'admin@gmail.com'),'ADMIN');


SELECT *
FROM APPUSER